include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    always_declare_return_types: true
    prefer_single_quotes: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_dynamic_calls: true
    avoid_annotating_with_dynamic: true

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  exclude:
    - lib/**.g.dart

formatter:
  trailing_commas: preserve
